/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_jnihash_JniHash */

#ifndef _Included_org_example_jnihash_JniHash
#define _Included_org_example_jnihash_JniHash
#ifdef __cplusplus
extern "C" {
#endif
#undef org_example_jnihash_JniHash_D_LEAF
#define org_example_jnihash_JniHash_D_LEAF 33410L
#undef org_example_jnihash_JniHash_D_INTR
#define org_example_jnihash_JniHash_D_INTR 33667L
/*
 * Class:     org_example_jnihash_JniHash
 * Method:    sha2_context
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_example_jnihash_JniHash_sha2_1context
  (JNIEnv *, jobject);

/*
 * Class:     org_example_jnihash_JniHash
 * Method:    sha2_update
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniHash_sha2_1update
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     org_example_jnihash_JniHash
 * Method:    sha2_256_doFinal
 * Signature: ([B[BI)I
 */
JNIEXPORT jint JNICALL Java_org_example_jnihash_JniHash_sha2_1256_1doFinal
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     org_example_jnihash_JniHash
 * Method:    sha2_unsafe
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniHash_sha2_1unsafe
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_example_jnihash_JniHash
 * Method:    sha2_unsafe_fixed_padding
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniHash_sha2_1unsafe_1fixed_1padding
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_example_jnihash_JniHash
 * Method:    sha2_intermediate_state
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_example_jnihash_JniHash_sha2_1intermediate_1state
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_example_jnihash_JniHash
 * Method:    sha2_256_768_lastBlock
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniHash_sha2_1256_1768_1lastBlock
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_example_jnihash_JniHash
 * Method:    sha2_free_state
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniHash_sha2_1free_1state
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
