/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_jnihash_JniShake */

#ifndef _Included_org_example_jnihash_JniShake
#define _Included_org_example_jnihash_JniShake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_jnihash_JniShake
 * Method:    shake256_context
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_jnihash_JniShake_shake256_1context
  (JNIEnv *, jobject);

/*
 * Class:     org_example_jnihash_JniShake
 * Method:    shake256_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniShake_shake256_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_jnihash_JniShake
 * Method:    shake256_update
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniShake_shake256_1update
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_example_jnihash_JniShake
 * Method:    shake256_doFinal
 * Signature: (JI[BI)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniShake_shake256_1doFinal
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint);

/*
 * Class:     org_example_jnihash_JniShake
 * Method:    shake256_unsafe
 * Signature: (JIJI)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniShake_shake256_1unsafe
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     org_example_jnihash_JniShake
 * Method:    shake256_sphincs_init_native
 * Signature: ([BIZ)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniShake_shake256_1sphincs_1init_1native
  (JNIEnv *, jobject, jbyteArray, jint, jboolean);

/*
 * Class:     org_example_jnihash_JniShake
 * Method:    shake256_unsafe_with_seed
 * Signature: (JIJI)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniShake_shake256_1unsafe_1with_1seed
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     org_example_jnihash_JniShake
 * Method:    shake256_unsafe_with_seed_robust
 * Signature: (JIJI)V
 */
JNIEXPORT void JNICALL Java_org_example_jnihash_JniShake_shake256_1unsafe_1with_1seed_1robust
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
